CREATE DATABASE brainbuster;

CREATE TABLE Admins (
    AdminID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Gender VARCHAR(1) NOT NULL,
    Email VARCHAR(50) NOT NULL,
	UserName VARCHAR(30) NOT NULL UNIQUE,
	NickName VARCHAR(30) NOT NULL,
    Pass VARCHAR(60) Not Null,
	RegDate DATE NOT NULL

);
ALTER TABLE Admins AUTO_INCREMENT=1;


#more than one students can be assigned more than one courses
create table AssignedCourses(
    CourseID INT NOT NULL,
    StdID INT NOT NULL,
    
    FOREIGN KEY (CourseID) REFERENCES Courses(CourseID),
	FOREIGN KEY (StdID) REFERENCES Students(StdID),

	PRIMARY KEY (CourseID, StdID)
);


CREATE TABLE Badges(
BID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
BName VARCHAR(255) NOT NULL,
BDetail TEXT NOT NULL
);
ALTER TABLE Badges AUTO_INCREMENT=1;


CREATE TABLE Courses (
    CourseID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CourseName VARCHAR(10) NOT NULL
);
ALTER TABLE Courses MODIFY COLUMN CourseName text;
ALTER TABLE Courses AUTO_INCREMENT=1;
alter table courses add column Status int;
alter table courses add column InstructorID int;
ALTER TABLE courses
ADD FOREIGN KEY (InstructorID) REFERENCES Instructors(InstructorID);


CREATE TABLE Instructors (
    InstructorID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Gender VARCHAR(1) NOT NULL,
    Email VARCHAR(50) NOT NULL,
	UserName VARCHAR(30) NOT NULL UNIQUE,
	NickName VARCHAR(30) NOT NULL,
    Pass VARCHAR(60) Not Null,
    RegDate DATE NOT NULL
);
ALTER TABLE Instructors AUTO_INCREMENT=1;



CREATE TABLE Links(
LinkID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
Link TEXT NOT NULL,
StID INT NOT NULL,
FOREIGN KEY (StID) REFERENCES Stages(StID)
);
ALTER TABLE Links AUTO_INCREMENT=1;


CREATE TABLE Questions (
	
    QID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Questions TEXT NOT NULL,
    A TEXT NOT NULL,
    B TEXT NOT NULL,
	C TEXT NOT NULL,
    D TEXT NOT NULL,
    Answer varchar(1) NOT NULL,
    Explanation TEXT NOT NULL,
    Difficulty INT NOT NULL,
	StID INT NOT NULL,
	
    FOREIGN KEY (StID) REFERENCES Stages(StID)
);
ALTER TABLE Questions AUTO_INCREMENT=1;


CREATE TABLE Score(
StdID INT NOT NULL,
StID INT NOT NULL,
Score INT NOT NULL,
FOREIGN KEY (StdID) REFERENCES Students(StdID),
FOREIGN KEY (StID) REFERENCES Stages(StID),

PRIMARY KEY (StdID, StID)
);


CREATE TABLE Stages(
StID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
StTitle VARCHAR(255) NOT NULL,
CourseID INT NOT NULL,
FOREIGN KEY (CourseID) REFERENCES Courses(CourseID)
);
ALTER TABLE Stages AUTO_INCREMENT=1;


CREATE TABLE StudentBadges(
StdID INT NOT NULL,
BID INT NOT NULL,
FOREIGN KEY (StdID) REFERENCES Students(StdID),
FOREIGN KEY (BID) REFERENCES Badges(BID)
);


CREATE TABLE Students (
    StdID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Gender VARCHAR(1) NOT NULL,
    Email VARCHAR(50) NOT NULL,
	UserName VARCHAR(30) NOT NULL UNIQUE,
	NickName VARCHAR(30) NOT NULL,
    Pass VARCHAR(60) Not Null,
    RegDate DATE NOT NULL,
    DateOfLastLogin DATE

);
ALTER TABLE Students AUTO_INCREMENT=1;